### ISSUE TITLE
macro sarge breaks line before docpart

### ISSUE THREAD

**Issue by Daimonion1980** [Kyllingene/sarge#9]
Hello

While learning rust I stumbled over your project. I like your approach to not build against a lot of dependencies. 👍 

I worked through your project and found the help examples/help.rs and also the doc description of the sarge macro ([this thing](https://github.com/Kyllingene/sarge/blob/5d069e47f3170a11595052b10f9a01ee927b5eda/src/macros.rs#L127)).

But the behavior differs. While in the example/help.rs the output is 
$tag {space} $env {space} : $doc

the output from the sarge macro is
$tag {space} $env {space} : 
$doc

There are "\n" in the var_tag macro ([there](https://github.com/Kyllingene/sarge/blob/5d069e47f3170a11595052b10f9a01ee927b5eda/src/macros.rs#L84), [there](https://github.com/Kyllingene/sarge/blob/5d069e47f3170a11595052b10f9a01ee927b5eda/src/macros.rs#L88) and [there](https://github.com/Kyllingene/sarge/blob/5d069e47f3170a11595052b10f9a01ee927b5eda/src/macros.rs#L95))
Oh forgot the last one [this one](https://github.com/Kyllingene/sarge/blob/5d069e47f3170a11595052b10f9a01ee927b5eda/src/macros.rs#L100)

After removing this "\n" the output looks better to me.

Because I'm pretty new to rust and don't know if I break something I did not create a PR to solve this, but I think the solution should be pretty fast forward. ;) 

Another little improvement would be when the doc string gets a line break. It continues directly under the colon. 
For design purposes it would be great if the string starts under the first char from its start.

Regards Daimonion

**Comment by Kyllingene** [comment]
Thanks for the interest! I use the help feature very little, thank you for investigating this. I'll fix it as soon as I can. 

I'm not certain about how the description continuation ought to work, though; if it continues at the colon, then a long enough prior section could lead to width limiting making it be extremely thin and almost unreadable, like this:

```
--very-long-argument-name : this
                                                   is
                                                   the
                                                   description
```

Perhaps it could place the description indented on the next line iff there's not enough room after the flags section?

**Comment by Daimonion1980** [comment]
Thanks for the fast response!

> I'm not certain about how the description continuation ought to work, though; if it continues at the colon, then a long enough prior section could lead to width limiting making it be extremely thin and almost unreadable, like this:

At the moment your example prints the last statement in this way:

![image](https://github.com/Kyllingene/sarge/assets/12880413/c24eae82-e1bd-4f00-8199-903511aabe1f)

When changing [this](https://github.com/Kyllingene/sarge/blob/master/src/help.rs#L20) 6 to an 8 your example prints the last statement in this way which is fine:

![image](https://github.com/Kyllingene/sarge/assets/12880413/0b1722bb-fc03-4db3-9002-00760ea08c0e)

**Comment by Kyllingene** [comment]
I got to my PC and tried out a very contrived example, and I realize now that it's not reasonable to expect the args section to get that long:

![image](https://github.com/Kyllingene/sarge/assets/69094702/c791b0da-fdf6-4ad3-932c-f74af1a5310f)

Even with all that, it's still not too compressed, so I'll go with your suggestion. Thanks for the input!

**Comment by Kyllingene** [comment]
Commit [393f967](https://github.com/Kyllingene/sarge/commit/393f967cdd901f348f6be6efb3676a3f14ee3f35) should fix this issue, let me know if there's anything still wrong.
